
Custom Gobs
-----------

This is a proposal based on tests and a prototype in development which
allows external graphic rendering engines to integrate directly within
R3 view system.

It may be referred to as the CGR (Custom Gob Renderer) API within the
body of this document.

We aim to expand the gob API. As some ideas get implemented or revised,
this document will serve as a basis for its documentation.


Why?
++++

Its not because we use an alternate graphic engine that we want to
relinquish the use of View's easy to use graphic engine.

This is even more true when we want to use a *REBOL* GUI package and
just embed some other graphic system into the same window.


A quick note about the R3 rendering pipeline
++++++++++++++++++++++++++++++++++++++++++++

The R3 view has basically 3 levels of graphic management, only one which
is directly accessible from within the interpreter.

* Gob! - The purely Rebol Hi-level interface which is like a handle to
the internals.
* Compositor - Although not a clear-cut layer in and of itself, it
really does act as middle layer in the view system. It reads the gob
information tree and manages what is rendered and how to layer them,
eventually forking off to lower-level AGG routines.
* AGG - Anti Grain Geometry engine - is the low-level view processing
workhorse. Its a relatively fast and flexible CPU-based 2D vectorial
rendering engine.

This proposal integrates an API within the gob! system which is detected
and managed by the compositing engine.

The compositor is where the raster creation is launched within view's
graphics pipeline and the compositor knows about things like visibility,
sizing, and transparency information.

The compositor also scans the gob in order to know what rendering
process to call internally, so its a logical place to fork to external
renderers.


A quick note about the prototype in development
+++++++++++++++++++++++++++++++++++++++++++++++

The prototype is not using some of the features in this proposal because
parts of view are closed since they require management from the r3 core
(its a datatype! after all).

The prototype already addresses changes in the compositor and uses an
alternative (slow) method to manage gob-relative custom data.

The current focus is mainly in testing and identifying strengths and
weaknesses in the current API in order to make it more flexible, at
minimal cost in RAM, speed and man-hours.


Rendering Speed considerations
++++++++++++++++++++++++++++++

Using any graphic engine WITHIN another obviously comes at a price and
this price is speed.

The prototype is the test bed in which we will take decisions in order
to achieve acceptable performance. Based on empiric testing, we may
provide switches in the system to increase refresh rates at the cost of
some capabilities. For example, some rendering engines can render
directly within an OS window. some possible side-effect is that allowing
this will prevent AGG from drawing over the custom gob. In such a case,
and if no alternative is possible, as switch will be added [EDIT: see
link:#OS-Level_integration_of_view_and_custom_Renderers[render modes]]
to let you decide if you need raw-performance, or flexibility.

The goal is to be able to reach very high refresh rates (100fps is a
minimum) at very high screen resolutions (1440x900 minimum), basically,
allowing effective real-time graphics for apps such as video editing,
video-playback, games, and other high-throughput applications.

The system must not impede the advantages of a rendering engine by
slowing it down at the display stage.


What rendering engines are we targeting?
++++++++++++++++++++++++++++++++++++++++

The list is short but covers a wide range of requirements

* *_OpenGL_*: The most widely used hardware-able gfx lib in the
world(http://www.opengl.org).
* *_DirectX_*: The fastest and most integrated hardware-able gfx API on
windows, it also has many productive gaming libs
(http://www.microsoft.com/games/en-us/aboutgfw/pages/directx.aspx).
* *_Cairo_*: has a very active community, is used by many applications,
OSes and toolsets. It has many nice integrated
features.(http://cairographics.org/)
* *_Image Magick_*: Image magick is used by many high-end softwares and
is probably one of the oldest graphic rendering packages in the world.
It started as an SGI project. It allows rendering at any bit depth,
supports HDRI natively and allows MASSIVE direct to disk rendering (tens
of GBs of data per render is easily managed). It has a wide range of
effects, supports just about all image formats known to man.
(http://www.imagemagick.org/script/index.php)
* *_WebKit's WebCore or Gecko_* used by many browsers, it would allow
embedding standards' compliant web content directly within view
applications with minimal effort.(http://webkit.org/)


The proposed custom GOB API at a glance
---------------------------------------


Creating a custom GOB renderer
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is done via the host-kit/extension API requiring you to bind
external C/C++ rendering code to the custom GOB API.

Basically, in the Compiled Extension code you:

1.  Define a struct (referred in this document as *_custom_gob_data_*)
which will hold renderer data for each gob instances. You must store
this struct within the *rebol_gob->custom* member.
2.  Create and setup a *gob_renderer* struct so it holds callbacks for
your external renderer, allowing the internal engine to execute your own
code. it has the following hooks:
* *on_custom()/on_internal()* allows you to build or destroy your
_custom_gob_data_ struct, and link it to the R3 allocated *_rebol_gob_*.
This is also where you handle any rendering engine needs.
* *on_append()/on_remove()* Called when a gob is about to be
added/removed to another gob.
* *on_data()* given user data in Rebol Extension format, this will
usually result in setting up native (Binary) data within
*_rebol_gob->custom_*. The information is actually stored in usual gob
fashion, within *_rebol_gob->data_*.
* *on_render()* (re)generate the custom's gob image. You are given an
RGBA buffer and rectangle area information. If your gob would be clipped
from the display, it is not even called for rendering. A member within
the *_rebol_gob_* struct already indicates if your renderer should blend
itself using alpha channel masks to optimize rendering when its not
required.
3.  *RegisterGobRenderer()* supplying your gob_renderer_hooks struct and
a string that will be usable as a word within Rebol.


Using custom gobs
~~~~~~~~~~~~~~~~~

If you require a gob to be managed by an external renderer, use the
renderer: field.

`   my-gob: make gob! [` +
`       size: 100x100 ` +
`       offset: 0x0 ` +
`       renderer: 'MOAGL ` +
`       custom: [sphere [0 0 0] 30.0 blue]` +
`   ]`

This will invoke the appropriate renderer on it.

The reason we use _CUSTOM:_ instead of _DATA:_ is that higher-level APIs
(ex: R3 GUI ) will need the _DATA:_ field for their own data storage.


Default Custom Renderers
^^^^^^^^^^^^^^^^^^^^^^^^

You can also use the 'SET-DEFAULT-CUSTOM-RENDERER function. This
prevents you from having to set the _RENDERER:_ field all the time. You
must still use the _CUSTOM:_ field in order to tell view that this gob
uses the default renderer.

`   set-default-custom-renderer: 'MOAGL ` +
`   ` +
`   my-gob: make gob! [` +
`       size: 100x100 ` +
`       offset: 0x0 ` +
`       custom: [sphere [0 0 0] 30.0 blue]` +
`   ]`


Changes required in current Rebol version (A107) to make it work
----------------------------------------------------------------

`   Note: This is in a constent state of flux and for now is only intended as an example` +
`         of what to expect, eventually.`

Here is a list of files which will need editing. I include some of the
changes I can already *guess* will be needed.

Note that these are still highly subjective assessments at this point.
Not everything here might be possible or feasible, based on knowledge
which is kept within the core.

Some of these have already been applied to the prototype and are
undergoing testing right now.


host_graphics.c
~~~~~~~~~~~~~~~

* Add a linked list or array in order to stored registered External
Renderers
* Define RegisterGobRenderer()
* Define GetGobRender()
* Define macros to call External renderer hooks


r3core.lib
~~~~~~~~~~

* Call hooks on custom gobs at appropriate low-frequency moments
(creation/destruction/linking, etc)

Basically, when the interpreter is managing the gob! It should allow a
callback within the hostkit. Additionally, we could even support this
for AGG rendering, allowing nice tricks using compiled code to
complement the internal rendering (filters, codecs, etc).

* support gob/custom: [... data ...] ; ANY legal host-kit data
* support gob/renderer: 'rendererID ; a word, ex: 'OpenGL


reb_gob.h
~~~~~~~~~

* Add *_custom_* member to *_rebol_gob struct_*
* add a new entry in the *_GOB_TYPES_* enum: *_GOBT_CUSTOM_*
* define IS_GOB_CUSTOM(g) (GOB_CONTENT(g) && GOB_TYPE(g) == GOBT_CUSTOM)
* define the *_gob_renderer_* struct something like (its changing daily
and is not up to date):

`   struct gob_renderer {` +
`       //*************** ` +
`       //     payload` +
`       //*************** ` +
`       REBYTE *renderer_info; // a one-sentence string identifying this renderer` +
`       ` +
`       ` +
`       //*************** ` +
`       //     hooks` +
`       //*************** ` +
`       ` +
`       // when the gob is given fresh data by assigning to its `*`gob/custom:`*` field` +
`       REBINT (* on_data)(REBGOB *gob);` +
`       ` +
`       // when the gob is converted to a custom type (custom: [... data ...])` +
`       // note: also called when its created as a custom gob directly` +
`       REBINT (* on_custom)(REBGOB *gob);` +
`       ` +
`       // when the gob leaves custom state.  This happens when you assign` +
`       // user data to the gob other than custom: data (ex:  my_custom_gob/draw: [line 0x0 100x100])` +
`       REBINT (* on_internal)(REBGOB *gob);` +
`       ` +
`       // when gob is appended to a gob (pane) ` +
`       // note: converting to custom when its already appended, should also call this immediately after on_internal().` +
`       REBINT (* on_append)(REBGOB *gob, REBGOB *parent);  ` +
`       ` +
`       // when removed from a gob (pane)` +
`       // note: when an gob is switched from one pane to another, it should call ` +
`       REBINT (* on_remove)(REBGOB *gob, REBGOB *parent);  on_append() immediately.` +
`       ` +
`       // when rendering is required by compositor and GOBT_EXTERNAL is set. ` +
`       // a function which receives an RGB (bgr) & alpha image buffer array (not image type), and x,y,w,h, specs.` +
`       REBINT (* on_render